logging:
  level:
    root: DEBUG
    org.hibernate.type.descriptor.sql: trace
  file:
    path: target/logs

server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      validation-timeout: 40000
    sql-script-encoding: UTF-8
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

#local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testDB;mode=MySQL;DB_CLOSE_DELAY=-1
    username: ENC(bn7gNC9SEFcbStq4dDtVuw==)
    password: ENC(px9ud7xYJVB4/MW8CSH7kw==)
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

my:
  test:
    encValue: ENC(lXghc3bqo998+jeOxIB2S6LhMtHZZZ75)